server:
  port: 8083

spring:
  application:
    name: cart-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce_carts

    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    com.ecommerce.cart: DEBUG